FROM nvidia/cuda:11.0.3-runtime-ubuntu20.04

ENV DEBIAN_FRONTEND=noninteractive 

RUN apt update -y && \
    apt install -y python3 python3-pip git htop vim

WORKDIR /app
RUN pip install quimb pyrofiler cartesian-explorer opt_einsum
RUN pip install --no-binary pynauty pynauty
RUN cd qtree && pip install . 
RUN pip install .
RUN pip install pdbpp

ENTRYPOINT ["bash"]