# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"cache": "qaoa_ansatz_complexity.ipynb",
         "ex": "qaoa_ansatz_complexity.ipynb",
         "graph": "qaoa_ansatz_complexity.ipynb",
         "quimb_time_energy": "Compare merged ix.ipynb",
         "qtensor_time_ansatz_merged": "Compare merged ix.ipynb",
         "qtensor_time_ansatz": "Compare merged ix.ipynb",
         "qtensor_time_energy": "Compare merged ix.ipynb",
         "QAOAMergedSimulator": "Compare merged ix.ipynb",
         "qtensor_time_energy_merged": "Compare merged ix.ipynb",
         "cli": "index.ipynb",
         "qiskit_time": "Speed_comparison.ipynb",
         "quimb_time": "Speed_comparison.ipynb",
         "qtensor_time": "qaoa_ansatz_complexity.ipynb",
         "gen_time_data": "Speed_comparison.ipynb",
         "plot_xar_data": "Speed_comparison.ipynb",
         "time_comparison_xarray": "Speed_comparison.ipynb",
         "ql": "Speed_comparison.ipynb",
         "circuit": "Time_vs_FLOP.ipynb",
         "tn": "Time_vs_FLOP.ipynb",
         "peo": "Time_vs_FLOP.ipynb",
         "sim_costs": "Time_vs_FLOP.ipynb",
         "sum_flops": "Time_vs_FLOP.ipynb",
         "step_flops": "Time_vs_FLOP.ipynb",
         "max_mem": "Time_vs_FLOP.ipynb",
         "SEED": "Time_vs_FLOP.ipynb",
         "EDGE_IDX_FOR_SEED": "Time_vs_FLOP.ipynb",
         "EDGE_IDX_FOR_SEED_JLSE": "Time_vs_FLOP.ipynb",
         "sim_profile": "Time_vs_FLOP.ipynb",
         "step_sim_time": "Time_vs_FLOP.ipynb",
         "plot_with_filter": "Time_vs_FLOP.ipynb",
         "get_log_flops_vs_matmul": "Time_vs_FLOP.ipynb",
         "time_vs_flops_plot": "Time_vs_FLOP.ipynb",
         "parallel": "qaoa_ansatz_complexity.ipynb",
         "ansatz_circ": "qaoa_ansatz_complexity.ipynb",
         "qtensor_tw": "qaoa_ansatz_complexity.ipynb",
         "qaoa_ansatz_time": "qaoa_ansatz_complexity.ipynb"}

modules = ["compare_merged_ix.py",
           "speed_comparison.py",
           "time_vs_flop.py",
           "__init__.py",
           "qaoa_ansatz_complexity.py"]

doc_url = "https://danlkv.github.io/qtensor-specs/"

git_url = "https://github.com/danlkv/qtensor"

def custom_doc_links(name): return None
