# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"ex": "Time_vs_FLOP.ipynb",
         "graph": "Time_vs_FLOP.ipynb",
         "qiskit_time": "Speed_comparison.ipynb",
         "quimb_time": "Speed_comparison.ipynb",
         "qtensor_time": "Speed_comparison.ipynb",
         "gen_time_data": "Speed_comparison.ipynb",
         "plot_xar_data": "Speed_comparison.ipynb",
         "time_comparison_xarray": "Speed_comparison.ipynb",
         "ql": "Speed_comparison.ipynb",
         "circuit": "Time_vs_FLOP.ipynb",
         "tn": "Time_vs_FLOP.ipynb",
         "peo": "Time_vs_FLOP.ipynb",
         "sim_costs": "Time_vs_FLOP.ipynb",
         "sum_flops": "Time_vs_FLOP.ipynb",
         "step_flops": "Time_vs_FLOP.ipynb",
         "max_mem": "Time_vs_FLOP.ipynb",
         "SEED": "Time_vs_FLOP.ipynb",
         "EDGE_IDX_FOR_SEED": "Time_vs_FLOP.ipynb",
         "EDGE_IDX_FOR_SEED_JLSE": "Time_vs_FLOP.ipynb",
         "sim_profile": "Time_vs_FLOP.ipynb",
         "step_sim_time": "Time_vs_FLOP.ipynb",
         "plot_with_filter": "Time_vs_FLOP.ipynb",
         "get_log_flops_vs_matmul": "Time_vs_FLOP.ipynb",
         "time_vs_flops_plot": "Time_vs_FLOP.ipynb",
         "cli": "index.ipynb"}

modules = ["speed_comparison.py",
           "time_vs_flop.py",
           "__init__.py"]

doc_url = "https://danlkv.github.io/qtensor-specs/"

git_url = "https://github.com/danlkv/qtensor"

def custom_doc_links(name): return None
